<?php

$existingArticles = [
    'farmer-id-card-online-guide-2026' => [
        'slug' => 'farmer-id-card-online-guide-2026',
        'title' => 'Farmer ID Card Online 2026 Guide | SETU Suvidha',
        'title_en' => 'Farmer ID Card Online Guide 2026',
        'description' => 'Step-by-step Farmer ID card guidance, eligibility, and practical benefits for PM Kisan and agriculture workflows.',
        'excerpt' => 'Complete farmer ID article with process, benefits, and FAQ support for multi-state users.',
        'icon' => 'leaf',
        'color' => 'green',
        'category' => 'Farmer Services',
        'date' => '19 Feb 2026',
        'read_time' => '12 min',
        'date_published' => '2026-02-19',
        'date_modified' => '2026-02-19',
        'view' => 'reviews.farmer-id-card-guide',
        'og_image' => '/images/og/review-farmer-id-card-online-guide-2026.png',
    ],
    'ladki-bahin-yojana-maharashtra-2026' => [
        'slug' => 'ladki-bahin-yojana-maharashtra-2026',
        'title' => 'Ladki Bahin Yojana Maharashtra 2026 | SETU Suvidha',
        'title_en' => 'Ladki Bahin Yojana 2026',
        'description' => 'Eligibility, document list, and application support details for Ladki Bahin Yojana in Maharashtra.',
        'excerpt' => 'Updated practical guide for beneficiaries and service operators.',
        'icon' => 'heart',
        'color' => 'pink',
        'category' => 'Government Schemes',
        'date' => '19 Feb 2026',
        'read_time' => '15 min',
        'date_published' => '2026-02-19',
        'date_modified' => '2026-02-19',
        'view' => 'reviews.ladki-bahin-yojana',
        'og_image' => '/images/og/review-ladki-bahin-yojana-maharashtra-2026.png',
    ],
    'mahabocw-bandkam-kamgar-yojana-2026' => [
        'slug' => 'mahabocw-bandkam-kamgar-yojana-2026',
        'title' => 'MAHABOCW Bandkam Kamgar 2026 Guide | SETU Suvidha',
        'title_en' => 'MAHABOCW 2026 Guide',
        'description' => 'Comprehensive MAHABOCW scheme coverage for registration, benefits, and operational support.',
        'excerpt' => 'Detailed builder-worker welfare scheme guide for Maharashtra users.',
        'icon' => 'hard-hat',
        'color' => 'amber',
        'category' => 'Government Schemes',
        'date' => '20 Feb 2026',
        'read_time' => '25 min',
        'date_published' => '2026-02-20',
        'date_modified' => '2026-02-20',
        'view' => 'reviews.mahabocw-bandkam-kamgar',
        'og_image' => '/images/og/review-mahabocw-bandkam-kamgar-yojana-2026.png',
    ],
    'nirgam-utara-download' => [
        'slug' => 'nirgam-utara-download',
        'title' => 'Nirgam Utara Download 2026 Guide | SETU Suvidha',
        'title_en' => 'Nirgam Utara Guide',
        'description' => 'Nirgam Utara meaning, usage, and practical application format with downloadable guidance.',
        'excerpt' => 'Practical school transfer and certificate support guide for applicants.',
        'icon' => 'file-text',
        'color' => 'orange',
        'category' => 'Education Documents',
        'date' => '21 Feb 2026',
        'read_time' => '14 min',
        'date_published' => '2026-02-21',
        'date_modified' => '2026-02-21',
        'view' => 'reviews.nirgam-utara-guide',
        'og_image' => '/images/og/review-nirgam-utara-download.png',
    ],
];

$newDefinitions = [
    'pm-kisan-status-check-2026' => [
        'topic_mr' => 'PM किसान स्टेटस चेक',
        'topic_en' => 'PM Kisan Status Check',
        'title_en' => 'PM Kisan Status Check 2026 Guide',
        'title_mr' => 'PM किसान स्टेटस चेक 2026: हप्ता, eKYC आणि FTO Tracking',
        'description' => 'PM Kisan beneficiary status, installment tracking, eKYC and payment troubleshooting guide for Maharashtra users.',
        'excerpt' => 'PM Kisan payment का अडकतो, status codes कसे वाचायचे, eKYC कधी complete मानायचे आणि field-level correction कसा करायचा याचा practical मार्गदर्शक.',
        'icon' => 'sprout',
        'color' => 'green',
        'accent' => '#16a34a',
        'hero_gradient' => 'linear-gradient(135deg, #064e3b 0%, #166534 45%, #065f46 100%)',
        'category' => 'Farmer Scheme / कृषी योजना',
        'focus' => 'PM Kisan installment status tracking and eKYC closure workflow',
        'portal' => 'pmkisan.gov.in',
        'timeline' => '24h to 7 days (status updates)',
        'fee' => 'No portal fee',
        'output' => 'Beneficiary + installment payment status',
        'extra_overview' => 'Rft Signed, FTO Generated, Payment Failed असे terms applicant ला समजत नाहीत. Counter-level translation आणि action mapping केल्यास grievance load कमी होतो.',
        'highlights' => [
            'Beneficiary status आणि installment status वेगळे तपासा.',
            'eKYC pending असल्यास payment release अडू शकतो.',
            'Aadhaar-bank seeding mismatch हे frequent root cause आहे.',
            'FTO generated म्हणजे immediate credit नाही.',
        ],
        'steps' => [
            'Farmer ID/Aadhaar वापरून beneficiary record उघडा.',
            'Installment-wise status log तयार करा.',
            'eKYC state verify करून required correction note करा.',
        ],
        'documents' => [
            'Aadhaar copy',
            'Bank passbook front page',
            'Previous installment proof (if available)',
        ],
        'mistakes' => [
            'Failure code न वाचता same attempt repeat करणे.',
            'Outdated mobile number वर OTP अपेक्षित ठेवणे.',
        ],
        'notes' => [
            'Error-code quick chart counter वर ठेवा.',
            'Every failed case ला correction owner assign करा.',
        ],
        'related_links' => [
            ['label' => 'e-KYC Update Online Guide', 'url' => '/reviews/e-kyc-update-online-guide'],
            ['label' => 'Satbara 7/12 Download Guide', 'url' => '/reviews/satbara-utara-online-download-guide'],
            ['label' => 'Farmer ID Card Guide', 'url' => '/reviews/farmer-id-card-online-guide-2026'],
        ],
    ],
    'kcc-loan-online-apply-maharashtra' => [
        'topic_mr' => 'KCC कर्ज अर्ज',
        'topic_en' => 'KCC Loan Online Apply',
        'title_en' => 'KCC Loan Online Apply Maharashtra Guide',
        'title_mr' => 'KCC Loan Online Apply Maharashtra: अर्ज ते Bank Approval Workflow',
        'description' => 'KCC loan online application flow with branch validation, crop finance checks, and approval-readiness strategy.',
        'excerpt' => 'KCC loan मध्ये online application नंतर bank branch verification हा critical stage असतो. Land records, crop data आणि repayment profile कसे align करायचे ते या guide मध्ये दिले आहे.',
        'icon' => 'badge-indian-rupee',
        'color' => 'emerald',
        'accent' => '#059669',
        'hero_gradient' => 'linear-gradient(135deg, #052e16 0%, #065f46 45%, #064e3b 100%)',
        'category' => 'Farmer Finance',
        'focus' => 'KCC loan approval quality with document and branch-stage readiness',
        'portal' => 'Bank/Agri loan digital channels',
        'timeline' => '7 to 21 working days',
        'fee' => 'Bank rules based service charge',
        'output' => 'KCC loan sanction / query status',
        'extra_overview' => 'Operators ने pre-screen checklist ठेवली तर applicant ला repeated branch visits कमी होतात आणि sanction decision clear timeline मध्ये मिळतो.',
        'highlights' => [
            'Online submit नंतर branch scrutiny decisive असते.',
            '7/12 आणि crop details consistency अत्यंत महत्त्वाची.',
            'Existing liabilities disclose करणे mandatory ठेवा.',
            'Sanction letter terms Marathi मध्ये explain करा.',
        ],
        'steps' => [
            'Applicant crop cycle आणि funding need map करा.',
            'Relevant branch आणि account linkage verify करा.',
            'Draft application + land data cross-check करा.',
        ],
        'documents' => [
            '7/12 and 8A references',
            'Bank passbook copy',
            'Crop declaration details',
        ],
        'mistakes' => [
            'Area/acre data wrong units मध्ये टाकणे.',
            'Outstanding loan history hide करणे.',
        ],
        'notes' => [
            'Branch query log maintain करा.',
            'Sanction letter pre-brief देऊन misunderstanding टाळा.',
        ],
        'related_links' => [
            ['label' => 'PM Kisan Status Guide', 'url' => '/reviews/pm-kisan-status-check-2026'],
            ['label' => 'Satbara Guide', 'url' => '/reviews/satbara-utara-online-download-guide'],
            ['label' => 'Farmer ID Card Guide', 'url' => '/reviews/farmer-id-card-online-guide-2026'],
        ],
    ],
    'aadhaar-update-form-download-2026' => [
        'topic_mr' => 'आधार अपडेट फॉर्म',
        'topic_en' => 'Aadhaar Update Form',
        'title_en' => 'Aadhaar Update Form Download 2026 Guide',
        'title_mr' => 'Aadhaar Update Form Download 2026: नाव, पत्ता, DOB Correction Guide',
        'description' => 'Aadhaar update form workflow for demographic corrections with proper proof mapping and submission validation.',
        'excerpt' => 'Aadhaar correction करताना online vs center route कधी वापरायचा, proof mismatch कसा टाळायचा आणि URN tracking कसे करायचे याचा practical guide.',
        'icon' => 'fingerprint',
        'color' => 'blue',
        'accent' => '#2563eb',
        'hero_gradient' => 'linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 45%, #1e40af 100%)',
        'category' => 'Aadhaar Services',
        'focus' => 'Aadhaar demographic update quality and rejection prevention',
        'portal' => 'uidai.gov.in',
        'timeline' => '3 to 15 days',
        'fee' => 'UIDAI update charge as applicable',
        'output' => 'Updated Aadhaar record / update status',
        'extra_overview' => 'Name transliteration आणि DOB proof rules न समजल्यामुळे rejection वाढतो. Field-by-field proof mapping वापरल्यास accuracy लक्षणीय सुधारते.',
        'highlights' => [
            'Field-specific proof list आधी final करा.',
            'Online channel आणि biometric channel वेगळे ठेवा.',
            'URN/EID tracking नोंद अनिवार्य आहे.',
            'Address update मध्ये pin code consistency तपासा.',
        ],
        'steps' => [
            'Correction field type identify करा.',
            'Latest form/instructions डाउनलोड करा.',
            'Proof-document pairing verify करा.',
        ],
        'documents' => [
            'Aadhaar base record',
            'POI/POA/DOB proof as required',
            'Active mobile for OTP',
        ],
        'mistakes' => [
            'POI आणि POA proof mix-up करणे.',
            'URN note न ठेवणे.',
        ],
        'notes' => [
            'Spelling read-back practice वापरा.',
            'Update request copy + proof scans archive ठेवा.',
        ],
        'related_links' => [
            ['label' => 'e-KYC Update Guide', 'url' => '/reviews/e-kyc-update-online-guide'],
            ['label' => 'Voter ID Apply Guide', 'url' => '/reviews/voter-id-card-apply-online-maharashtra'],
            ['label' => 'PAN Apply Guide', 'url' => '/reviews/pan-card-apply-online-guide-2026'],
        ],
    ],
    'voter-id-card-apply-online-maharashtra' => [
        'topic_mr' => 'मतदार ओळखपत्र ऑनलाइन अर्ज',
        'topic_en' => 'Voter ID Apply Online',
        'title_en' => 'Voter ID Card Apply Online Maharashtra Guide',
        'title_mr' => 'Voter ID Apply Online Maharashtra: Form 6/8, EPIC Status आणि BLO Verification',
        'description' => 'Voter ID online registration and correction guide with form selection, BLO verification, and EPIC tracking.',
        'excerpt' => 'Form-6 नवीन नोंदणी, Form-8 correction, address transfer आणि EPIC status tracking यासाठी Marathi + English practical process map.',
        'icon' => 'vote',
        'color' => 'indigo',
        'accent' => '#4f46e5',
        'hero_gradient' => 'linear-gradient(135deg, #312e81 0%, #3730a3 50%, #1e1b4b 100%)',
        'category' => 'Citizen ID Services',
        'focus' => 'Voter registration and correction workflow with constituency verification',
        'portal' => 'voters.eci.gov.in',
        'timeline' => '7 to 30 days',
        'fee' => 'No government fee for basic form flow',
        'output' => 'Voter entry + EPIC status',
        'extra_overview' => 'Wrong form selection मुळे पूर्ण cycle reset होऊ शकतो. त्यामुळे application type selection हा पहिला quality gate ठेवणे महत्त्वाचे आहे.',
        'highlights' => [
            'Form-6/8/7 चे उद्देश वेगळे आहेत.',
            'BLO verification preparedness ठेवणे आवश्यक.',
            'Constituency mapping चुकीचे झाल्यास delay होतो.',
            'EPIC number generation पर्यंत tracking ठेवा.',
        ],
        'steps' => [
            'Applicant case classify करा (new/correction/transfer).',
            'Correct form चुनून personal details भरा.',
            'Address proof + age proof upload quality check करा.',
        ],
        'documents' => [
            'Age proof',
            'Current address proof',
            'Photo and mobile details',
        ],
        'mistakes' => [
            'Wrong constituency निवडणे.',
            'BLO call/visit ignore करणे.',
        ],
        'notes' => [
            'Polling map reference counter वर ठेवा.',
            'Transfer case मध्ये old voter data आधी घ्या.',
        ],
        'related_links' => [
            ['label' => 'Aadhaar Update Guide', 'url' => '/reviews/aadhaar-update-form-download-2026'],
            ['label' => 'PAN Online Guide', 'url' => '/reviews/pan-card-apply-online-guide-2026'],
            ['label' => 'Self Declaration Guide', 'url' => '/reviews/self-declaration-format-marathi-download'],
        ],
    ],
    'pan-card-apply-online-guide-2026' => [
        'topic_mr' => 'PAN कार्ड ऑनलाइन अर्ज',
        'topic_en' => 'PAN Card Apply Online',
        'title_en' => 'PAN Card Apply Online Guide 2026',
        'title_mr' => 'PAN Card Apply Online 2026: New PAN, Correction आणि e-PAN Flow',
        'description' => 'PAN application and correction workflow with identity alignment, proof quality and e-PAN tracking.',
        'excerpt' => 'PAN form मध्ये नाव, DOB, father name mismatch मुळे rejection होतो. New apply आणि correction flows साठी clear operator-ready process या guide मध्ये दिला आहे.',
        'icon' => 'credit-card',
        'color' => 'purple',
        'accent' => '#7c3aed',
        'hero_gradient' => 'linear-gradient(135deg, #581c87 0%, #7e22ce 45%, #4c1d95 100%)',
        'category' => 'PAN Services',
        'focus' => 'PAN new and correction filing quality with accurate proof alignment',
        'portal' => 'Protean / UTIITSL',
        'timeline' => '7 to 20 days',
        'fee' => 'Application type based fee',
        'output' => 'PAN allotment / correction status',
        'extra_overview' => 'New PAN, correction PAN आणि reprint या वेगवेगळ्या प्रक्रिया आहेत. चुकीचा flow वापरल्यास time आणि fee दोन्ही वाया जातात.',
        'highlights' => [
            'Name + DOB + father name match अनिवार्य आहे.',
            'Application type चुकीचा निवडू नका.',
            'Photo/signature spec fail झाल्यास rejection येतो.',
            'e-PAN आणि physical dispatch tracking वेगळे ठेवा.',
        ],
        'steps' => [
            'Case type final करा: new/correction/reprint.',
            'Relevant form channel निवडा.',
            'Core fields proof अनुसार validate करा.',
        ],
        'documents' => [
            'Identity proof',
            'Address proof',
            'DOB proof and photo/signature',
        ],
        'mistakes' => [
            'Aadhaar spelling mismatch ignore करणे.',
            'Acknowledgement number हरवणे.',
        ],
        'notes' => [
            '4-field verbal confirmation policy ठेवा.',
            'Correction cases साठी change-log maintain करा.',
        ],
        'related_links' => [
            ['label' => 'Aadhaar Update Guide', 'url' => '/reviews/aadhaar-update-form-download-2026'],
            ['label' => 'Income Certificate Guide', 'url' => '/reviews/income-certificate-online-maharashtra-guide'],
            ['label' => 'Self Declaration Guide', 'url' => '/reviews/self-declaration-format-marathi-download'],
        ],
    ],
    'setu-kendra-registration-maharashtra' => [
        'topic_mr' => 'सेतू केंद्र नोंदणी',
        'topic_en' => 'Setu Kendra Registration',
        'title_en' => 'Setu Kendra Registration Maharashtra Guide',
        'title_mr' => 'Setu Kendra Registration Maharashtra: Setup, Compliance आणि Daily SOP',
        'description' => 'Setu Kendra registration and operations guide with setup, compliance, service stack and daily control model.',
        'excerpt' => 'Setu Kendra सुरू करताना registration पेक्षा जास्त महत्त्वाचे असते process discipline. हा guide launch ते daily operations पर्यंत complete blueprint देतो.',
        'icon' => 'building-2',
        'color' => 'amber',
        'accent' => '#d97706',
        'hero_gradient' => 'linear-gradient(135deg, #78350f 0%, #b45309 45%, #92400e 100%)',
        'category' => 'Center Operations',
        'focus' => 'Setu center launch readiness with service quality governance',
        'portal' => 'District service administration channels',
        'timeline' => '2 to 6 weeks (setup stage)',
        'fee' => 'Registration/compliance dependent',
        'output' => 'Operational Setu service counter',
        'extra_overview' => 'Service menu demand-data शिवाय सुरू केल्यास early stage मध्ये citizen dissatisfaction वाढतो. त्यामुळे onboarding phase मध्ये SOP आणि checklist mandatory ठेवा.',
        'highlights' => [
            'Compliance + infra + SOP हे तीन pillars ठेवा.',
            'Top demand services ने सुरुवात करा.',
            'Token-to-delivery flow standard करा.',
            'Daily closure report operating habit बनवा.',
        ],
        'steps' => [
            'Location आणि footfall survey finalize करा.',
            'Compliance checklist district-wise verify करा.',
            'Service desk layout + hardware readiness पूर्ण करा.',
        ],
        'documents' => [
            'Operator identity and address records',
            'Shop/location proof',
            'Bank/account compliance documents',
        ],
        'mistakes' => [
            'Random services add करून focus हरवणे.',
            'No pending tracker ठेवणे.',
        ],
        'notes' => [
            'Bilingual service board trust वाढवतो.',
            'Top 20 services साठी ready checklist files ठेवा.',
        ],
        'related_links' => [
            ['label' => 'Maha e-Seva Kendra Start Guide', 'url' => '/reviews/maha-e-seva-kendra-start-guide'],
            ['label' => 'CSC Center Near Me Guide', 'url' => '/reviews/csc-center-near-me-maharashtra-guide'],
            ['label' => 'All Services Page', 'url' => '/services'],
        ],
    ],
    'csc-center-near-me-maharashtra-guide' => [
        'topic_mr' => 'CSC Center शोध',
        'topic_en' => 'CSC Center Near Me',
        'title_en' => 'CSC Center Near Me Maharashtra Guide',
        'title_mr' => 'CSC Center Near Me Maharashtra: Genuine Verification आणि Service Quality Check',
        'description' => 'How to find a reliable CSC center in Maharashtra with quality checks, service proof and fraud-safe workflow.',
        'excerpt' => 'Near me search करताना फक्त location न बघता service quality, receipt discipline आणि genuine workflow कसा verify करायचा याचा user-first guide.',
        'icon' => 'map-pin',
        'color' => 'cyan',
        'accent' => '#0891b2',
        'hero_gradient' => 'linear-gradient(135deg, #164e63 0%, #0e7490 50%, #155e75 100%)',
        'category' => 'CSC Operations',
        'focus' => 'CSC center discovery and trust validation workflow',
        'portal' => 'Official locator + local verification',
        'timeline' => '10 to 30 minutes verification',
        'fee' => 'Service specific',
        'output' => 'Verified service center selection',
        'extra_overview' => 'Fraud-safe service experience साठी three checks वापरा: service availability, pricing transparency आणि acknowledgement discipline.',
        'highlights' => [
            'Near-by म्हणजे reliable असे नसते.',
            'Receipt देणारा center प्राधान्य द्या.',
            'Rate-card visibility quality signal असतो.',
            'Data privacy policy विचारणे आवश्यक आहे.',
        ],
        'steps' => [
            'Required services list आधी तयार करा.',
            'Nearby centers short-list करा.',
            'Phone + on-site verification दोन्ही करा.',
        ],
        'documents' => [
            'Applicant ID copy',
            'Service-specific supporting papers',
            'Contactable mobile number',
        ],
        'mistakes' => [
            'No-receipt transaction accept करणे.',
            'Single source review वर final decision घेणे.',
        ],
        'notes' => [
            'Small trial service ने center evaluate करा.',
            'Acknowledgement and ETA written स्वरूपात घ्या.',
        ],
        'related_links' => [
            ['label' => 'Setu Kendra Registration Guide', 'url' => '/reviews/setu-kendra-registration-maharashtra'],
            ['label' => 'Maha e-Seva Startup Guide', 'url' => '/reviews/maha-e-seva-kendra-start-guide'],
            ['label' => 'Reviews Index', 'url' => '/reviews'],
        ],
    ],
    'hamipatra-format-marathi-pdf-download' => [
        'topic_mr' => 'हमीपत्र फॉरमॅट',
        'topic_en' => 'Hamipatra Format Marathi',
        'title_en' => 'Hamipatra Format Marathi PDF Download Guide',
        'title_mr' => 'हमीपत्र Format Marathi PDF: Drafting Structure आणि Submission Checklist',
        'description' => 'Marathi Hamipatra drafting guide with format structure, legal-safe wording and PDF-ready output.',
        'excerpt' => 'हमीपत्र लिहिताना context-specific wording, declaration block आणि print-ready formatting कसे ठेवायचे यासाठी practical step-by-step format guide.',
        'icon' => 'file-signature',
        'color' => 'orange',
        'accent' => '#ea580c',
        'hero_gradient' => 'linear-gradient(135deg, #7c2d12 0%, #c2410c 45%, #9a3412 100%)',
        'category' => 'Declaration Forms',
        'focus' => 'Hamipatra drafting quality for acceptance-ready submission',
        'portal' => 'Draft preparation + office submission channels',
        'timeline' => '15 to 40 minutes draft cycle',
        'fee' => 'Case and service counter dependent',
        'output' => 'Print-ready Hamipatra PDF',
        'extra_overview' => 'Template copy-paste पेक्षा use-case specific language वापरल्यास query rate कमी होतो आणि acceptance chances वाढतात.',
        'highlights' => [
            'Purpose line clear ठेवा.',
            'Identity fields complete भरा.',
            'Declaration paragraph specific लिहा.',
            'Date/place/signature block check करा.',
        ],
        'steps' => [
            'Use-case note करून scope define करा.',
            'Applicant details Marathi spelling सह verify करा.',
            'Draft body मध्ये liability/undertaking स्पष्ट लिहा.',
        ],
        'documents' => [
            'Applicant identity proof',
            'Address proof',
            'Case reference/supporting facts',
        ],
        'mistakes' => [
            'Generic text बदल न करता वापरणे.',
            'Signature block miss करणे.',
        ],
        'notes' => [
            'Template IDs तयार करून version control ठेवा.',
            'Final draft applicant read-back process ठेवा.',
        ],
        'related_links' => [
            ['label' => 'Hamipatra Service Page', 'url' => '/services/hamipatra-format-marathi'],
            ['label' => 'Self Declaration Guide', 'url' => '/reviews/self-declaration-format-marathi-download'],
            ['label' => 'Rajpatra Format Guide', 'url' => '/reviews/rajpatra-format-marathi-guide'],
        ],
    ],
    'self-declaration-format-marathi-download' => [
        'topic_mr' => 'स्वयंघोषणापत्र फॉरमॅट',
        'topic_en' => 'Self Declaration Format Marathi',
        'title_en' => 'Self Declaration Format Marathi Download Guide',
        'title_mr' => 'Self Declaration Format Marathi: Statement Writing आणि Error-Free Submission',
        'description' => 'Self declaration drafting guide in Marathi with factual writing structure and submission-safe formatting.',
        'excerpt' => 'स्वयंघोषणापत्र लिहिताना subject clarity, factual statements आणि verification-ready closure कसे ठेवायचे याचा field-ready practical guide.',
        'icon' => 'file-check-2',
        'color' => 'teal',
        'accent' => '#0f766e',
        'hero_gradient' => 'linear-gradient(135deg, #134e4a 0%, #0f766e 45%, #115e59 100%)',
        'category' => 'Declaration Forms',
        'focus' => 'Self declaration drafting quality and submission accuracy',
        'portal' => 'Service desk drafting + office submission',
        'timeline' => '10 to 25 minutes',
        'fee' => 'Service specific',
        'output' => 'Final self declaration document',
        'extra_overview' => 'Vague language वापरल्यास declaration weak मानला जातो. म्हणून fact-only statement approach वापरणे सर्वोत्तम आहे.',
        'highlights' => [
            'Subject line आणि purpose स्पष्ट ठेवा.',
            'Facts measurable भाषेत लिहा.',
            'Contradictory statements टाळा.',
            'Closure line + signature mandatory ठेवा.',
        ],
        'steps' => [
            'Declaration purpose confirm करा.',
            'Core identity fields verify करा.',
            'Point-wise factual body तयार करा.',
        ],
        'documents' => [
            'Identity proof',
            'Address proof',
            'Supporting application reference',
        ],
        'mistakes' => [
            'Emotion-heavy content वापरणे.',
            'Date/place missing ठेवणे.',
        ],
        'notes' => [
            'Use-case wise snippet bank तयार ठेवा.',
            'PDF final करण्याआधी spell audit करा.',
        ],
        'related_links' => [
            ['label' => 'Self Declaration Service Page', 'url' => '/services/self-declaration-form-marathi'],
            ['label' => 'Hamipatra Guide', 'url' => '/reviews/hamipatra-format-marathi-pdf-download'],
            ['label' => 'Income Certificate Guide', 'url' => '/reviews/income-certificate-online-maharashtra-guide'],
        ],
    ],
    'income-certificate-online-maharashtra-guide' => [
        'topic_mr' => 'उत्पन्नाचा दाखला अर्ज',
        'topic_en' => 'Income Certificate Online',
        'title_en' => 'Income Certificate Online Maharashtra Guide',
        'title_mr' => 'Income Certificate Online Maharashtra: अर्ज, Scrutiny आणि Approval Guide',
        'description' => 'Income certificate application flow with family income validation, scrutiny readiness and approval tracking.',
        'excerpt' => 'उत्पन्नाचा दाखला online भरताना family income proofs, objection response आणि final certificate verification कसे manage करायचे यासाठी complete operator guide.',
        'icon' => 'landmark',
        'color' => 'rose',
        'accent' => '#e11d48',
        'hero_gradient' => 'linear-gradient(135deg, #881337 0%, #be123c 45%, #9f1239 100%)',
        'category' => 'Certificate Services',
        'focus' => 'Income certificate filing quality and objection handling',
        'portal' => 'Maharashtra service application channels',
        'timeline' => '7 to 30 days',
        'fee' => 'Application channel based',
        'output' => 'Income certificate issuance status',
        'extra_overview' => 'Family income breakup unclear असल्यास scrutiny objection येतो. Evidence-oriented filing केल्यास first-pass approval chance वाढतो.',
        'highlights' => [
            'Income sources structured पद्धतीने दाखवा.',
            'Family details consistency ठेवा.',
            'Objection notices ला deadline मध्ये respond करा.',
            'Issued certificate fields verify करा.',
        ],
        'steps' => [
            'Family income map तयार करा.',
            'Form fields income proof नुसार भरा.',
            'Submission नंतर scrutiny status नियमित check करा.',
        ],
        'documents' => [
            'Identity and address proofs',
            'Income source evidences',
            'Family declaration/supporting records',
        ],
        'mistakes' => [
            'Income period उल्लेख न करणे.',
            'Objection notice ignore करणे.',
        ],
        'notes' => [
            'Income proof ला category tags द्या.',
            'Final certificate handover आधी spelling check करा.',
        ],
        'related_links' => [
            ['label' => 'Income Certificate Service Page', 'url' => '/services/income-certificate-application-maharashtra'],
            ['label' => 'Caste Certificate Guide', 'url' => '/reviews/caste-certificate-documents-maharashtra'],
            ['label' => 'Self Declaration Guide', 'url' => '/reviews/self-declaration-format-marathi-download'],
        ],
    ],
    'caste-certificate-documents-maharashtra' => [
        'topic_mr' => 'जातीचा दाखला कागदपत्रे',
        'topic_en' => 'Caste Certificate Documents',
        'title_en' => 'Caste Certificate Documents Maharashtra Guide',
        'title_mr' => 'Caste Certificate Documents Maharashtra: Proof Matrix आणि Scrutiny Strategy',
        'description' => 'Caste certificate document architecture guide with lineage mapping, proof sequencing and scrutiny readiness.',
        'excerpt' => 'जातीच्या दाखल्यासाठी primary + lineage proofs कसे तयार करायचे, scrutiny queries कसे handle करायचे आणि rejection कसे कमी करायचे याचा structured guide.',
        'icon' => 'folder-check',
        'color' => 'violet',
        'accent' => '#7c3aed',
        'hero_gradient' => 'linear-gradient(135deg, #4c1d95 0%, #6d28d9 50%, #5b21b6 100%)',
        'category' => 'Certificate Services',
        'focus' => 'Caste certificate filing readiness with lineage proof continuity',
        'portal' => 'Maharashtra certificate processing channels',
        'timeline' => 'Case-based scrutiny timeline',
        'fee' => 'Application channel based fee',
        'output' => 'Caste certificate application/scrutiny status',
        'extra_overview' => 'Current ID proofs पुरेसे नसतात; historical continuity न दाखवता फाइल टाकल्यास query rate वाढतो. त्यामुळे lineage-first documentation करा.',
        'highlights' => [
            'Primary caste proof + lineage continuity दोन्ही दाखवा.',
            'Family relation chain structured ठेवा.',
            'Old records readable scans मध्ये द्या.',
            'Query response ला index reference द्या.',
        ],
        'steps' => [
            'Family lineage map तयार करा.',
            'Primary आणि supporting proofs categorize करा.',
            'Indexed file format मध्ये submission packet तयार करा.',
        ],
        'documents' => [
            'Applicant identity and address proof',
            'Lineage related supporting records',
            'Historical caste reference documents',
        ],
        'mistakes' => [
            'Random documents without lineage chain submit करणे.',
            'Old records unreadable ठेवणे.',
        ],
        'notes' => [
            'Lineage chart visual format मध्ये तयार करा.',
            'Name spellings across all proofs reconcile करा.',
        ],
        'related_links' => [
            ['label' => 'Caste Certificate Service Page', 'url' => '/services/caste-certificate-form-maharashtra'],
            ['label' => 'Income Certificate Guide', 'url' => '/reviews/income-certificate-online-maharashtra-guide'],
            ['label' => 'Rajpatra Format Guide', 'url' => '/reviews/rajpatra-format-marathi-guide'],
        ],
    ],
    'rajpatra-format-marathi-guide' => [
        'topic_mr' => 'राजपत्र मसुदा फॉरमॅट',
        'topic_en' => 'Rajpatra Format Marathi',
        'title_en' => 'Rajpatra Format Marathi Guide',
        'title_mr' => 'Rajpatra Format Marathi: Notice Drafting, Annexure Order आणि Legal Clarity',
        'description' => 'Rajpatra/gazette format guide with proper Marathi drafting structure, annexure control and submission quality.',
        'excerpt' => 'राजपत्र मसुद्यात wording accuracy, declaration structure आणि annexure indexing योग्य ठेवण्यासाठी practical drafting + review workflow.',
        'icon' => 'scale',
        'color' => 'fuchsia',
        'accent' => '#c026d3',
        'hero_gradient' => 'linear-gradient(135deg, #701a75 0%, #a21caf 45%, #86198f 100%)',
        'category' => 'Gazette Notice',
        'focus' => 'Rajpatra drafting quality and publication-ready document preparation',
        'portal' => 'Gazette notice submission channels',
        'timeline' => 'Draft cycle 1 to 5 days',
        'fee' => 'Case and publication type dependent',
        'output' => 'Rajpatra draft + submission packet',
        'extra_overview' => 'राजपत्रात ambiguous language टाळा. Concise, factual आणि legally coherent wording ठेवल्यास office-level query कमी होते.',
        'highlights' => [
            'Title आणि subject line legal style मध्ये ठेवा.',
            'Change statement specific लिहा.',
            'Annexure numbering strict ठेवा.',
            'Final proofread शिवाय submit करू नका.',
        ],
        'steps' => [
            'Use-case define करून draft objective लॉक करा.',
            'Body text मध्ये reason + declaration blocks ठेवा.',
            'Annexure list आणि index sheet synchronize करा.',
        ],
        'documents' => [
            'Identity/address supporting documents',
            'Change-specific evidence documents',
            'Declaration/affidavit records (as required)',
        ],
        'mistakes' => [
            'Generic wording वापरून context miss करणे.',
            'Annexure refs body मध्ये न देणे.',
        ],
        'notes' => [
            'Clause library maintain करा.',
            'PDF print-test अनिवार्य ठेवा.',
        ],
        'related_links' => [
            ['label' => 'Rajpatra Service Page', 'url' => '/services/rajpatra-gazette-format-marathi'],
            ['label' => 'Hamipatra Format Guide', 'url' => '/reviews/hamipatra-format-marathi-pdf-download'],
            ['label' => 'Self Declaration Guide', 'url' => '/reviews/self-declaration-format-marathi-download'],
        ],
    ],
    'satbara-utara-online-download-guide' => [
        'topic_mr' => 'सातबारा उतारा डाउनलोड',
        'topic_en' => 'Satbara Utara Download',
        'title_en' => 'Satbara Utara Online Download Guide',
        'title_mr' => 'Satbara (7/12) Utara Online Download: Survey Search आणि Record Verification',
        'description' => 'Satbara 7/12 online download process with district-taluka-village mapping and record integrity checks.',
        'excerpt' => '7/12 उतारा शोधताना survey/gat नंबर, owner details आणि latest record validation कसे करायचे यासाठी practical bilingual workflow.',
        'icon' => 'map',
        'color' => 'lime',
        'accent' => '#65a30d',
        'hero_gradient' => 'linear-gradient(135deg, #365314 0%, #4d7c0f 45%, #3f6212 100%)',
        'category' => 'Land Records',
        'focus' => 'Satbara lookup and secure download validation for land-service workflows',
        'portal' => 'Maharashtra land records portal',
        'timeline' => '5 to 20 minutes',
        'fee' => 'Portal/service channel dependent',
        'output' => '7/12 land record copy',
        'extra_overview' => 'एक digit survey mismatch मुळे wrong land record येतो. म्हणून jurisdiction + survey validation हा mandatory first step ठेवा.',
        'highlights' => [
            'District-taluka-village selection अचूक करा.',
            'Survey/Gat नंबर cross-check करा.',
            'Owner name आणि area fields verify करा.',
            'Downloaded copy timestamp note करा.',
        ],
        'steps' => [
            'Land location details आधी confirm करा.',
            'Portal search parameters careful fill करा.',
            'Record fields validate करूनच download finalize करा.',
        ],
        'documents' => [
            'Survey/Gat reference details',
            'Owner name reference',
            'Previous land record copy (for cross-check)',
        ],
        'mistakes' => [
            'Wrong village context वापरणे.',
            'Outdated record वापरून submission करणे.',
        ],
        'notes' => [
            'Downloaded file naming standard ठेवा.',
            'Land-related cases मध्ये dual backup ठेवा.',
        ],
        'related_links' => [
            ['label' => 'Satbara Service Page', 'url' => '/services/satbara-7-12-utara-online-maharashtra'],
            ['label' => 'PM Kisan Status Guide', 'url' => '/reviews/pm-kisan-status-check-2026'],
            ['label' => 'KCC Loan Guide', 'url' => '/reviews/kcc-loan-online-apply-maharashtra'],
        ],
    ],
    'e-kyc-update-online-guide' => [
        'topic_mr' => 'e-KYC अपडेट',
        'topic_en' => 'e-KYC Update Online',
        'title_en' => 'e-KYC Update Online Guide',
        'title_mr' => 'e-KYC Update Online: OTP, Biometric आणि Failure Recovery Workflow',
        'description' => 'e-KYC update troubleshooting guide covering OTP failures, biometric fallback and sync-delay handling.',
        'excerpt' => 'e-KYC failed, OTP issues, Aadhaar mismatch, biometric retry अशा frequent समस्यांसाठी operator-friendly diagnostic workflow.',
        'icon' => 'shield-check',
        'color' => 'sky',
        'accent' => '#0284c7',
        'hero_gradient' => 'linear-gradient(135deg, #082f49 0%, #0369a1 45%, #0c4a6e 100%)',
        'category' => 'Digital Verification',
        'focus' => 'e-KYC failure diagnosis and closure tracking',
        'portal' => 'Scheme/platform specific verification channels',
        'timeline' => '1 to 5 days depending on sync',
        'fee' => 'Channel dependent',
        'output' => 'e-KYC completion status',
        'extra_overview' => 'Failure reason classify न करता random retries केल्यास lock issues वाढतात. Error-code based approach वापरा.',
        'highlights' => [
            'OTP fail आणि data mismatch वेगळे handle करा.',
            'Biometric fallback route तयार ठेवा.',
            'Sync delay ला immediate failure समजू नका.',
            'Case closure note applicant ला द्या.',
        ],
        'steps' => [
            'Failure category identify करा.',
            'OTP route verify करून retry protocol follow करा.',
            'Required असल्यास biometric-assisted path वापरा.',
        ],
        'documents' => [
            'Aadhaar details',
            'Active mobile linkage reference',
            'Related scheme/application ID',
        ],
        'mistakes' => [
            'Error-code capture न करणे.',
            'Unplanned multiple retries करणे.',
        ],
        'notes' => [
            'Failure code sheet handy ठेवा.',
            'Post-success dependent service statusही verify करा.',
        ],
        'related_links' => [
            ['label' => 'PM Kisan Status Guide', 'url' => '/reviews/pm-kisan-status-check-2026'],
            ['label' => 'Aadhaar Update Guide', 'url' => '/reviews/aadhaar-update-form-download-2026'],
            ['label' => 'Voter ID Guide', 'url' => '/reviews/voter-id-card-apply-online-maharashtra'],
        ],
    ],
    'maha-e-seva-kendra-start-guide' => [
        'topic_mr' => 'महा ई-सेवा केंद्र सुरूवात',
        'topic_en' => 'Maha e-Seva Kendra Start',
        'title_en' => 'Maha e-Seva Kendra Start Guide',
        'title_mr' => 'Maha e-Seva Kendra Start Guide: Launch Plan, Service Stack आणि Growth SOP',
        'description' => 'Maha e-Seva startup guide with compliance, infrastructure, team SOP, and growth-oriented service operations.',
        'excerpt' => 'Maha e-Seva Kendra launch करताना compliance, process standardization आणि citizen trust-building एकत्रित कसे करायचे यासाठी practical roadmap.',
        'icon' => 'rocket',
        'color' => 'yellow',
        'accent' => '#ca8a04',
        'hero_gradient' => 'linear-gradient(135deg, #713f12 0%, #a16207 45%, #854d0e 100%)',
        'category' => 'Center Operations',
        'focus' => 'Maha e-Seva center launch and scale process model',
        'portal' => 'Maha e-Seva administrative workflow channels',
        'timeline' => '30 to 90 days (launch to stabilize)',
        'fee' => 'Setup and compliance dependent',
        'output' => 'Operational Maha e-Seva center model',
        'extra_overview' => 'Startup stage मध्ये quality gates न ठेवता volume chase केल्यास rejection आणि complaints वाढतात. SOP-first scaling वापरणे अधिक सुरक्षित आहे.',
        'highlights' => [
            'Launch phase आणि scale phase वेगळे plan करा.',
            'Service-wise TAT dashboard चालू ठेवा.',
            'Document QA gate शिवाय submission करू नका.',
            'Citizen communication scripts standard करा.',
        ],
        'steps' => [
            'Center setup roadmap phases मध्ये divide करा.',
            'Service mix demand analysis करा.',
            'Daily metrics + weekly review cadence सेट करा.',
        ],
        'documents' => [
            'Operator and center compliance records',
            'Infrastructure and onboarding documentation',
            'Service authorization/supporting paperwork',
        ],
        'mistakes' => [
            'No training SOP ठेवणे.',
            'Pending-case ownership define न करणे.',
        ],
        'notes' => [
            'Top rejection reasons dashboard visible ठेवा.',
            'Monthly process audit करा.',
        ],
        'related_links' => [
            ['label' => 'Setu Kendra Registration Guide', 'url' => '/reviews/setu-kendra-registration-maharashtra'],
            ['label' => 'CSC Center Near Me Guide', 'url' => '/reviews/csc-center-near-me-maharashtra-guide'],
            ['label' => 'Subscription Page', 'url' => '/subscription'],
        ],
    ],
];

$buildArticle = static function (string $slug, array $d): array {
    $topicMr = $d['topic_mr'];
    $topicEn = $d['topic_en'];
    $portal = $d['portal'];
    $timeline = $d['timeline'];
    $fee = $d['fee'];
    $output = $d['output'];

    $commonSteps = [
        $topicMr . ' साठी applicant details verify करा.',
        'Official channel (' . $portal . ') वर योग्य service mode निवडा.',
        'Submission reference number सुरक्षित जतन करा.',
        'Pending असल्यास timeline-based follow-up schedule ठेवा.',
    ];

    $commonDocs = [
        'Identity proof (photo + readable details)',
        'Address proof (latest and valid)',
        'Mobile number for OTP/alerts',
    ];

    $commonMistakes = [
        'नाम/दिनांक/ID mismatch तपासल्याशिवाय submit करणे.',
        'Document scan blur ठेवणे.',
        'Acknowledgement/reference number न जतन करणे.',
        'Status recheck timeline न देणे.',
    ];

    $commonNotes = [
        'Counter वर pre-submission checklist visible ठेवा.',
        'Marathi + English field names एकसारखे वापरा.',
        'Applicant ला next action लिखित द्या.',
        'Case closure नंतर digital archive maintain करा.',
    ];

    $faqs = [
        [
            'q' => $topicMr . ' साठी online process पूर्णपणे घरी करता येतो का?',
            'a' => 'काही stages online होतात, पण काही cases मध्ये assisted verification किंवा office touchpoint लागू शकतो.',
        ],
        [
            'q' => 'Application reject होण्याचे मुख्य कारण काय असते?',
            'a' => 'Data mismatch आणि incomplete proof हे सर्वात common कारण आहेत.',
        ],
        [
            'q' => 'Status किती दिवसांनी check करावा?',
            'a' => 'Submission नंतर scheduled interval ठेवा; ' . $timeline . ' हा practical reference window आहे.',
        ],
        [
            'q' => 'Service fee किती आहे?',
            'a' => $fee . ' (local processing model नुसार variations लागू शकतात).',
        ],
        [
            'q' => 'Final output काय मिळते?',
            'a' => $output . ' मिळते; final handover आधी details verify करणे आवश्यक आहे.',
        ],
    ];

    return [
        'slug' => $slug,
        'title' => $d['title_en'] . ' | SETU Suvidha',
        'title_en' => $d['title_en'],
        'title_mr' => $d['title_mr'],
        'description' => $d['description'],
        'excerpt' => $d['excerpt'],
        'icon' => $d['icon'],
        'color' => $d['color'],
        'accent' => $d['accent'],
        'hero_gradient' => $d['hero_gradient'],
        'category' => $d['category'],
        'focus' => $d['focus'],
        'date' => '25 Feb 2026',
        'read_time' => $d['read_time'] ?? '14 min',
        'date_published' => '2026-02-25',
        'date_modified' => '2026-02-25',
        'view' => 'reviews.' . $slug,
        'og_image' => '/images/og/review-' . $slug . '.png',
        'quick_stats' => [
            ['label' => 'Official Channel', 'value' => $portal],
            ['label' => 'Typical Timeline', 'value' => $timeline],
            ['label' => 'Fee Window', 'value' => $fee],
            ['label' => 'Expected Output', 'value' => $output],
        ],
        'tags' => $d['tags'] ?? [$topicEn, $topicMr, 'Maharashtra', 'Guide'],
        'overview' => [
            $topicMr . ' (' . $topicEn . ') साठी हा guide field-level practical workflow वर तयार केला आहे. उद्देश्य म्हणजे submission quality वाढवणे आणि rejection कमी करणे.',
            'Maharashtra मधील applicants आणि operators दोघांसाठी Marathi + English मिश्र clarity ठेवून process explain केला आहे. प्रत्येक step मध्ये data consistency आणि document readiness वर भर दिला आहे.',
            'जर standardized workflow वापरला तर visit repeat ratio कमी होतो, service turnaround सुधारतो आणि applicant trust वाढतो. म्हणून हा guide checklist-driven approach recommend करतो.',
            $d['extra_overview'],
        ],
        'highlights' => array_merge($d['highlights'], [
            'Portal entry आणि document details line-by-line match ठेवा.',
            'Submission नंतर status tracking ला fixed cadence ठेवा.',
        ]),
        'practical_steps' => array_merge($d['steps'], $commonSteps),
        'documents' => array_merge($d['documents'], $commonDocs),
        'common_mistakes' => array_merge($d['mistakes'], $commonMistakes),
        'expert_notes' => array_merge($d['notes'], $commonNotes),
        'faqs' => isset($d['faqs']) ? array_merge($d['faqs'], $faqs) : $faqs,
        'related_links' => $d['related_links'],
    ];
};

$newArticles = [];
foreach ($newDefinitions as $slug => $definition) {
    $newArticles[$slug] = $buildArticle($slug, $definition);
}

return [
    'articles' => array_merge($existingArticles, $newArticles),
];
