<?php

return [
    'pages' => [
        'hamipatra-format-marathi' => [
            'slug' => 'hamipatra-format-marathi',
            'route_name' => 'services.landing.show',
            'view' => 'services.landing.hamipatra-format-marathi',
            'title' => 'Hamipatra Format Marathi | SETU Suvidha',
            'description' => 'Hamipatra format in Marathi with process, required details, affidavit workflow, and print-ready guidance for Setu and CSC operators.',
            'h1' => 'Hamipatra Format Marathi: Complete Guide',
            'hero_kicker' => 'Government Form Support',
            'category' => 'Affidavit and Declaration',
            'updated_at' => '2026-02-25',
            'og_image' => '/images/og/services-hamipatra.png',
            'intro' => [
                'Hamipatra is one of the most used documents at Setu Kendra and Maha e-Seva counters. Most users search for "hamipatra format marathi pdf", but they still face rejection because names, dates, and declaration language do not match official expectations.',
                'This guide is designed for Marathi and bilingual users. We explain exact field-level structure, not just a copy-paste sample. Every section is written for practical use in village, taluka, district, and city-level service centers.',
                'If your center handles daily certificates and affidavit support, standardizing Hamipatra drafting can reduce rework, increase same-day output, and improve customer trust. A single clean process helps both operators and applicants.',
                'Below you get template strategy, mandatory data points, verification tips, and printing workflow that can be implemented directly in your service counter routine.',
            ],
            'why_important' => [
                'Used across income proof, local declarations, and supporting affidavit workflows.',
                'Reduces application rejection when declaration text is consistent.',
                'Improves legal clarity for applicant intent and self-declaration.',
                'Helps operators maintain repeatable format quality.',
                'Saves drafting time during high-volume days.',
                'Builds trust when customer gets a professional print-ready document.',
            ],
            'steps' => [
                'Confirm applicant identity details exactly as per Aadhaar or official ID.',
                'Capture full address in a district-taluka-village compatible format.',
                'Select declaration reason and keep language purpose-specific.',
                'Add date, place, and applicant signature block with clarity.',
                'If witness details are required for local usage, include complete identifiers.',
                'Run spelling and number validation before print.',
                'Print on A4 with clean margin and readable font size.',
                'Store digital copy for future reference and correction history.',
            ],
            'required_documents' => [
                'Applicant photo identity proof',
                'Address proof',
                'Mobile number for confirmation',
                'Supporting document for declaration context',
                'Recent passport size photo if local office asks',
                'Previous reference number where applicable',
            ],
            'common_mistakes' => [
                'Mixing Marathi and English names inconsistently across lines',
                'Missing date or place in declaration block',
                'Unclear purpose statement that does not match application',
                'Incorrect taluka or district naming mismatch',
                'Unsigned applicant block before submission',
            ],
            'faqs' => [
                ['q' => 'Can Hamipatra be used for multiple services?', 'a' => 'Use service-specific declaration text whenever possible. Generic content can trigger clarification or rejection.'],
                ['q' => 'Should Hamipatra be in Marathi only?', 'a' => 'Marathi-first is preferred for local workflows, but bilingual format can be used where process supports it.'],
                ['q' => 'Is notarization always required?', 'a' => 'Not always. Requirement depends on the destination office and process category.'],
                ['q' => 'Can I print on normal A4 paper?', 'a' => 'Yes, in most cases A4 is accepted if content and signature blocks are complete and clear.'],
                ['q' => 'How to avoid rejection?', 'a' => 'Keep identity fields, purpose text, and date/place sections exact and verified before final print.'],
            ],
        ],

        'self-declaration-form-marathi' => [
            'slug' => 'self-declaration-form-marathi',
            'route_name' => 'services.landing.show',
            'view' => 'services.landing.self-declaration-form-marathi',
            'title' => 'Self Declaration Form Marathi | SETU Suvidha',
            'description' => 'Self declaration form Marathi guide with format structure, legal-safe text flow, checklist, and submission best practices.',
            'h1' => 'Self Declaration Form Marathi: Practical Format',
            'hero_kicker' => 'Self Declaration',
            'category' => 'Citizen Declaration',
            'updated_at' => '2026-02-25',
            'og_image' => '/images/og/services-self-declaration.png',
            'intro' => [
                'Self Declaration is a core supporting form for many applications where direct proof is pending or authority asks applicant confirmation in writing.',
                'Operators often use copied templates with outdated wording. This creates mismatch with current service requirement and causes return visits for correction.',
                'This page gives a production-ready framework that your center can standardize. You can use one base structure and adapt declaration lines by service context.',
                'For faster daily execution, keep identity, address, declaration body, and signature flow fixed, then swap only service-specific content.',
            ],
            'why_important' => [
                'Acts as applicant responsibility statement.',
                'Supports temporary proof gaps in document workflow.',
                'Improves transparency for service center and user.',
                'Prevents verbal-only claims in critical form processing.',
                'Useful in district-level and taluka-level service desks.',
                'Strengthens record quality during audits.',
            ],
            'steps' => [
                'Collect applicant basic details and match with ID.',
                'Write declaration statement with clear intent and scope.',
                'Mention service name and authority where document will be submitted.',
                'Include legal accountability line in plain language.',
                'Add date, place, and signature with printed name.',
                'Attach supporting copies as reference bundle.',
                'Re-check punctuation and number formatting.',
                'Save PDF record before handing over print.',
            ],
            'required_documents' => [
                'Identity proof',
                'Address proof',
                'Service application reference',
                'Any provisional supporting paper',
                'Contact details',
            ],
            'common_mistakes' => [
                'Declaration text too generic and non-actionable',
                'No mention of submission authority',
                'Address mismatch vs proof document',
                'No attachment mention in body',
                'Unsigned declaration at final handover',
            ],
            'faqs' => [
                ['q' => 'Is self declaration legally valid?', 'a' => 'It is valid as a signed applicant statement, subject to service authority rules.'],
                ['q' => 'Can it replace mandatory documents?', 'a' => 'No. It supports the workflow but does not replace hard mandatory proof where required.'],
                ['q' => 'Can I submit in English?', 'a' => 'Many offices accept bilingual format, but Marathi-first is preferred in local service contexts.'],
                ['q' => 'Do I need witness signature?', 'a' => 'Only when process asks for it explicitly.'],
                ['q' => 'Can the same format be reused?', 'a' => 'Yes, keep a base template and customize the declaration body per service.'],
            ],
        ],

        'income-certificate-application-maharashtra' => [
            'slug' => 'income-certificate-application-maharashtra',
            'route_name' => 'services.landing.show',
            'view' => 'services.landing.income-certificate-application-maharashtra',
            'title' => 'Income Certificate Application Maharashtra | SETU Suvidha',
            'description' => 'Income certificate application format and process for Maharashtra with document checklist, data validation steps, and rejection prevention tips.',
            'h1' => 'Income Certificate Application Maharashtra',
            'hero_kicker' => 'Revenue Certificate',
            'category' => 'Income Proof',
            'updated_at' => '2026-02-25',
            'og_image' => '/images/og/services-income-certificate.png',
            'intro' => [
                'Income Certificate is one of the highest demand services for students, scholarships, government benefits, and reservation-linked processes.',
                'Most delays happen because applicant family details, annual income breakdown, and occupation fields are not drafted clearly in the first attempt.',
                'This guide gives a practical operator workflow so that your center can collect data correctly, prepare clean application format, and reduce repeat visits.',
                'Whether your customer is from city or village region, use this structured flow to keep application quality consistent across all counters.',
            ],
            'why_important' => [
                'Required in scholarship and education support workflows.',
                'Frequently used in social welfare and subsidy applications.',
                'Needed for several reservation-category eligibility processes.',
                'Critical for validating annual family income claims.',
                'Direct impact on approval timelines if errors exist.',
                'High-volume service for Setu and CSC centers.',
            ],
            'steps' => [
                'Capture complete household member details first.',
                'Record all income sources with annual estimate.',
                'Validate occupation category and employer/farm details.',
                'Prepare declaration and supporting statement block.',
                'Attach mandatory proofs and reference numbers.',
                'Reconcile totals before print and submission.',
                'Generate final A4 print with date and signature blocks.',
                'Keep scanned copy and submission note in center records.',
            ],
            'required_documents' => [
                'Identity proof of applicant',
                'Address proof',
                'Ration card or family composition proof',
                'Income source proof where available',
                'Affidavit or declaration support document',
                'Passport photo if required in local office',
            ],
            'common_mistakes' => [
                'Incorrect annual total calculation',
                'Missing family member data',
                'Unclear occupation field',
                'No cross-check against attached proofs',
                'Unsigned declaration and date mismatch',
            ],
            'faqs' => [
                ['q' => 'Can income certificate be applied online?', 'a' => 'Yes, with proper document support and form quality through authorized service channels.'],
                ['q' => 'How long does it usually take?', 'a' => 'Timelines vary by district workload, but clean first submission always improves turnaround.'],
                ['q' => 'Is salary slip mandatory?', 'a' => 'Not always. Requirement depends on occupation type and available proof set.'],
                ['q' => 'Can students apply through parents?', 'a' => 'Yes, student workflows often require family income details and guardian records.'],
                ['q' => 'What is the biggest rejection reason?', 'a' => 'Income mismatch between form entry and supporting documents.'],
            ],
        ],

        'caste-certificate-form-maharashtra' => [
            'slug' => 'caste-certificate-form-maharashtra',
            'route_name' => 'services.landing.show',
            'view' => 'services.landing.caste-certificate-form-maharashtra',
            'title' => 'Caste Certificate Form Maharashtra | SETU Suvidha',
            'description' => 'Caste certificate form guidance for Maharashtra with data sequence, required records, submission workflow, and validation checklist.',
            'h1' => 'Caste Certificate Form Maharashtra: Filing Guide',
            'hero_kicker' => 'Category Certificate',
            'category' => 'Identity and Category Proof',
            'updated_at' => '2026-02-25',
            'og_image' => '/images/og/services-caste-certificate.png',
            'intro' => [
                'Caste Certificate applications demand high accuracy in lineage details, category naming, and historical proof attachments.',
                'Applicants often bring incomplete records, and operators must translate rough local data into a clean office-ready application format.',
                'This page provides a structured process for Setu and CSC operators to prepare forms confidently and reduce back-and-forth corrections.',
                'Use this workflow to keep caste name, sub-caste, district records, and document references synchronized from first draft itself.',
            ],
            'why_important' => [
                'Required for education reservation workflows.',
                'Needed for category-linked public recruitment benefits.',
                'Important for state and central document compliance.',
                'Depends on historical records and family lineage proof.',
                'Form quality strongly affects scrutiny speed.',
                'Frequent service in regional citizen centers.',
            ],
            'steps' => [
                'Capture applicant caste and sub-caste exactly as records indicate.',
                'Collect parental and ancestral supporting references.',
                'Record district and origin details carefully.',
                'Prepare declaration and affidavit support where needed.',
                'Attach educational or legacy documents in proper order.',
                'Cross-check names across all attachments.',
                'Generate clean final application print with signature block.',
                'Maintain digital copy with document index for follow-up.',
            ],
            'required_documents' => [
                'Applicant identity proof',
                'Address proof',
                'School leaving or legacy caste-related record',
                'Family member certificate copy if available',
                'Affidavit or declaration support',
                'Any district-level supporting endorsement',
            ],
            'common_mistakes' => [
                'Category spelling mismatch between form and proofs',
                'Missing sub-caste details where mandatory',
                'Incomplete family linkage references',
                'No index order in attachments',
                'Signature blocks left blank during print handover',
            ],
            'faqs' => [
                ['q' => 'Can old family certificate help?', 'a' => 'Yes, legacy references often strengthen the application when properly attached.'],
                ['q' => 'Is caste validity same as caste certificate?', 'a' => 'No, caste validity is separate and typically a later verification stage.'],
                ['q' => 'Can spelling differences cause rejection?', 'a' => 'Yes, even minor mismatches can delay verification or trigger re-submission.'],
                ['q' => 'Do all applicants need affidavit?', 'a' => 'Only when the process or record gap requires declaration support.'],
                ['q' => 'How to speed up approval?', 'a' => 'Submit a complete and internally consistent record bundle at first attempt.'],
            ],
        ],

        'rajpatra-gazette-format-marathi' => [
            'slug' => 'rajpatra-gazette-format-marathi',
            'route_name' => 'services.landing.show',
            'view' => 'services.landing.rajpatra-gazette-format-marathi',
            'title' => 'Rajpatra Gazette Format Marathi | SETU Suvidha',
            'description' => 'Rajpatra and Gazette notice format in Marathi with draft structure, use-cases, and submission-ready checklists for service operators.',
            'h1' => 'Rajpatra Gazette Format Marathi: Draft to Print',
            'hero_kicker' => 'Gazette Notice',
            'category' => 'Gazette and Legal Notice',
            'updated_at' => '2026-02-25',
            'og_image' => '/images/og/services-rajpatra.png',
            'intro' => [
                'Rajpatra drafting requires precision in legal narration, identity details, and public notice language quality.',
                'Operators commonly manage Marathi, English, and 7/12-linked affidavit variants. A standardized pattern is the fastest way to avoid drafting errors.',
                'This guide focuses on practical counter-level execution: from data intake to final print-ready text blocks.',
                'If your center provides Gazette notice preparation, this process will help maintain clarity, legal consistency, and professional output.',
            ],
            'why_important' => [
                'Used in name changes and public legal notices.',
                'Requires language precision and legal structure.',
                'Multiple format variants often confuse applicants.',
                'Draft quality impacts acceptance and publication flow.',
                'High-value service for advanced form centers.',
                'Needs repeatable template governance.',
            ],
            'steps' => [
                'Identify exact Rajpatra use-case before drafting.',
                'Select Marathi/English/combined format requirement.',
                'Collect identity records and reason statement.',
                'Draft notice text with legal-safe sentence structure.',
                'Insert date, location, and applicant confirmation line.',
                'Validate spellings of names and addresses twice.',
                'Prepare print version with consistent spacing and headings.',
                'Store digital source text for future amendment requests.',
            ],
            'required_documents' => [
                'Identity proof',
                'Address proof',
                'Reason-specific support documents',
                'Photo where process asks',
                'Signature-ready declaration draft',
            ],
            'common_mistakes' => [
                'Drafting wrong notice type for the use-case',
                'Mixing inconsistent language style in one notice',
                'Address and district data mismatch',
                'Missing declaration closure line',
                'No draft proofread before print',
            ],
            'faqs' => [
                ['q' => 'Can Rajpatra be prepared in Marathi only?', 'a' => 'Yes, if the receiving process accepts Marathi-only notice format.'],
                ['q' => 'Is English version mandatory?', 'a' => 'It depends on specific publication or authority requirement.'],
                ['q' => 'Can this be done in one visit?', 'a' => 'Yes, if applicant brings complete details and required proofs.'],
                ['q' => 'What is the biggest drafting risk?', 'a' => 'Incorrect legal wording for the intended notice category.'],
                ['q' => 'How to standardize center workflow?', 'a' => 'Use a fixed template library and strict pre-print validation checklist.'],
            ],
        ],

        'satbara-7-12-utara-online-maharashtra' => [
            'slug' => 'satbara-7-12-utara-online-maharashtra',
            'route_name' => 'services.landing.show',
            'view' => 'services.landing.satbara-7-12-utara-online-maharashtra',
            'title' => 'Satbara 7/12 Utara Online Maharashtra | SETU Suvidha',
            'description' => '7/12 Utara online workflow for Maharashtra with field guidance, verification checks, and support process for Setu and CSC operators.',
            'h1' => 'Satbara 7/12 Utara Online Maharashtra Guide',
            'hero_kicker' => 'Land Record Support',
            'category' => 'Land and Revenue Record',
            'updated_at' => '2026-02-25',
            'og_image' => '/images/og/services-satbara.png',
            'intro' => [
                '7/12 Utara (Satbara) is critical for land ownership reference, crop records, and multiple agriculture-linked workflows.',
                'Many applicants do not know survey details and land record naming format. Service center operators bridge this gap through structured intake and verification.',
                'This guide is designed to help you process Satbara support requests accurately while minimizing repeated corrections and office-level objections.',
                'Use this as a standard operating flow in your center when handling online lookup, print assistance, and follow-up document support.',
            ],
            'why_important' => [
                'Used in agriculture loan and subsidy processes.',
                'Needed for ownership and cultivation reference.',
                'Frequently requested for farm-related verifications.',
                'Errors in survey details create major delays.',
                'High-volume request category in rural counters.',
                'Standardized intake improves service turnaround.',
            ],
            'steps' => [
                'Collect district, taluka, village, and survey identifiers.',
                'Verify name spelling with supporting identity.',
                'Run online record lookup through approved workflow.',
                'Confirm land details with applicant before print.',
                'Highlight discrepancy if mutation is pending.',
                'Prepare clear print and explain usage scope.',
                'Maintain lookup reference for repeat requests.',
                'Guide user on correction path where mismatch exists.',
            ],
            'required_documents' => [
                'Applicant identity proof',
                'Land reference details (survey/gat number)',
                'Village and taluka details',
                'Supporting legacy papers if available',
                'Mobile contact for follow-up',
            ],
            'common_mistakes' => [
                'Wrong village or taluka selection',
                'Survey number transcription errors',
                'Assuming old owner name equals current entry',
                'Printing without applicant-side confirmation',
                'No note on mutation pending status',
            ],
            'faqs' => [
                ['q' => 'Is 7/12 Utara available online for all records?', 'a' => 'Most current records are available, but some legacy or disputed entries may need additional process steps.'],
                ['q' => 'Can I use printed copy immediately?', 'a' => 'For many workflows yes, but specific offices may ask for certified copy where required.'],
                ['q' => 'What if owner name is outdated?', 'a' => 'You must guide applicant to mutation/update process before relying on it for final submission.'],
                ['q' => 'Can CSC operator help in lookup?', 'a' => 'Yes, assisted lookup and data validation are common center services.'],
                ['q' => 'What is the most important detail?', 'a' => 'Correct district-taluka-village plus survey/gat mapping.'],
            ],
        ],
    ],
];
